# Generated by Django 4.1.7 on 2023-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0002_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
