# Generated by Django 4.1.7 on 2023-03-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0004_user_city_user_dic_user_todo_user_alter_city_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
