# Generated by Django 4.1.7 on 2023-03-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0005_alter_dic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
